In [1]:
import pandas as pd 
import plotly.express as px

In [ ]:
df = pd.read_csv('avocado-updated-2020.csv')
df.info()

In [ ]:
fig = df['geography'] == 'Boston'
px.line(df[fig] , x= 'date' , y='average_price',color ='type')

In [2]:
from jupyter_dash import JupyterDash
import dash_html_components as html 
import dash_bootstrap_components as dbc
import dash_core_components as dcc
from dash.dependencies import Input, Output

C:\Users\ysyss\AppData\Local\Temp\ipykernel_12840\895714773.py:2: UserWarning:
The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`
  import dash_html_components as html
C:\Users\ysyss\AppData\Local\Temp\ipykernel_12840\895714773.py:4: UserWarning:
The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`
  import dash_core_components as dcc

In [ ]:
app = JupyterDash(external_stylesheets=[dbc.themes.LUX])



#app layout
app.layout = html.Div(children = [
    
    html.Br([]),
    html.H1('Avocado price dash app', style = {'text-align':'center' ,  'color': 'white'}),
    html.P('25-1-2023 wensday plotly dash' , style = {'text-align':'center' , 'color': 'gray',"padding": "20px"}),
    
   
    
    #dropdown
    dcc.Dropdown(id='my-drop',
                options=[{'label':i , 'value':i}
                        for i in df['geography'].unique()]),
    
    #garph
    dcc.Graph(id='my-graph'),
    ])



@app.callback(
Output('my-graph', 'figure'),
Input('my-drop','value')
)
def update_graph(selected_geography):
    fillter_df = df[df['geography']==selected_geography ]
    line_chart = px.line(fillter_df , x='date' , y='average_price' , 
                         color='type' , 
                         title = f'Avocado price in {selected_geography}')
    
    return line_chart


if __name__ == '__main__':
    app.run_server(mode='inline') # 'inline' is to display here, rather than local host.

In [ ]:
from dash import Dash, dcc, html, Input, Output
import plotly.graph_objects as go
import numpy as np
from jupyter_dash import JupyterDash


app = JupyterDash(__name__) 
# app = Dash(__name__)


app.layout = html.Div([
    html.H4('Interactive plot with custom data source'),
    dcc.Graph(id="graph"),
    html.P("Number of bars:"),
    dcc.Slider(id="slider", min=2, max=10, value=4, step=1),
])


@app.callback(
    Output("graph", "figure"), 
    Input("slider", "value"))
def update_bar_chart(size):
    data = np.random.normal(3, 2, size=size) # fake data for example
    fig = go.Figure(
        data=[go.Bar(y=data)],
        layout_title_text="Native Plotly rendering in Dash"
    )
    return fig

# app.run()  
app.run_server(use_reloader=False, mode='inline') # Turn off reloader if inside Jupyter

# Best Exmaple

In [3]:
import seaborn as sns 
import plotly.express as px
df = sns.load_dataset("titanic")
df["survived"] = df["survived"].astype("str")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
app = JupyterDash(__name__)


class_label = ['First', 'Second', 'Third', 'None']


app.layout = html.Div([
                       html.H1("Titanic Dash App"),

                       dcc.Graph(id="graph"),

                       html.Label([
                                   "Survived/Not Survived",
                                    dcc.Dropdown(
                                        id='survive', 
                                        clearable=False,
                                        value= -1, 
                                        options=[{'label': "Survived", 'value': "1"},
                                                 {'label': "Not Survived", 'value': "0"},
                                                 {'label': "Both", 'value': -1}]
                                        )
                       ]),
                       
                       html.Br([]),

                       html.Label([
                                   "Class",
                                   dcc.RadioItems(
                                       id="class",
                                       options=[{'label':x, "value":x} for x in class_label],
                                       value='None',
                                       labelStyle={'display': 'inline-block'}
                                    )  
                                                        ])

                       
])


@app.callback(
    Output('graph', 'figure'),
    [Input("survive", "value"),
     Input("class", "value")]
)


def update_figure(val_survived, val_class):

    if  (val_class != "None") & (val_survived == -1) :

        test = df[df["class"] == val_class]
        return px.scatter(
        test, 
        x="age", 
        y="fare",
        render_mode="webgl",
        color="survived",
        title="Titanic"
        )

    elif (val_class == "None") & (val_survived != -1):

        test = df[df["survived"] == val_survived]
        return px.scatter(
        test, 
        x="age", 
        y="fare",
        render_mode="webgl",
        facet_row="class",
        title="Titanic"
        )
    elif (val_class == "None") & (val_survived == -1):

        test = df
        return px.scatter(
        test, 
        x="age", 
        y="fare",
        render_mode="webgl",
        color="survived",
        facet_row="class",
        hover_data=["survived"],
        title="Titanic: 1='Survived', 0='Not Survived'",
        )

    else:
        test = df[(df["class"] == val_class) & (df["survived"] == val_survived)] # filter for 0 or 1
        return px.scatter(
            test, 
            x="age", 
            y="fare",
            render_mode="webgl",
            title="Titanic",
            )


if __name__ == '__main__':
    app.run_server()

Dash is running on http://127.0.0.1:8050/

Dash app running on http://127.0.0.1:8050/